[tool.poetry]
name = "pyasic-api"
version = "0.1.1"
description = ""
authors = ["UpstreamData <brett@upstreamdata.ca>", "Ian Descôteaux <ian.descoteaux@pow.re>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
pyasic = "^0.37.4"
fastapi = {version = "^0.95.1"}
uvicorn = "^0.21.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
